### PR TITLE
update

### PR DESCRIPTION
**Pull request by MandipJoshi**
Changed minimum password length to 1 and maximum to 128(Changed to 128 cause bitwarden password generator also has maximum 128 character)
Changed selection color to #066a8c
Before:
image
After
image

Added new screenshot in readme.md
Added password generator link https://michal037.github.io/password-generator/ in readme.md

### CODE REVIEW

**Comment by michal037** [comment]
Hi, thank you for the feature request!
I like these changes. I'll add them soon, now I'm sick and browsing from my phone. I need to fix the CSS for Mozilla Firefox because I saw that the interface is not centering properly. I also want to add a note that you helped me improve this code.

**Comment by michal037** [comment]
I wonder too, who ever uses such long passwords? With 20 random characters and long server response times, no one can break it. Sooner, they will break into the account using social engineering or security vulnerabilities. I set 64 characters for convenience and a smaller range on the slider.

**Comment by MandipJoshi** [comment]
I hope you will get well soon.
Yes 64 password is good. But people may need to use 100 word password compulsory in some site like birwarden. And also I think the minimum character for generating password should be at least 7 or 8.
And in firefox also it seems to be fine.
image

**Comment by michal037** [comment]
> But people may need to use 100 word password compulsory in some site like birwarden.

Sure, it'll be useful in this case.

> And also I think the minimum character for generating password should be at least 7 or 8.

I agree! But now it is more universal, you can generate, for example, 4-6 digital pins, bit strings, hex numbers etc. It only depends on the selection of character groups. Sometimes I use this app like this.

> And in firefox also it seems to be fine.

Thank you very much for the verification. It is possible that they fixed this in one of the updates. I noticed the problem in 2019 as I was installing the software on the server and needed to generate a password.

**Comment by MandipJoshi** [comment]
> 4-6 digital pins, bit strings, hex numbers etc

oh i hadn't thought out it.

**Review by michal037 — COMMENTED** [review]
ok

**Pull request merged**
